### ISSUE TITLE
Better registration, Authentication, Restification, and IP logging and encrypting in the backend.

### ISSUE THREAD

**Issue by AbooMinister25** [cat-dev-group/catcord#51]
Alright, so far, our backend is pretty simple, you send a POST request to `/token`, get a token, and proceed to use that to interact with our API. What I want to do is add better registration, so requiring an email, username, and password, as well as restrict accounts per IP, and ratelimits on each endpoint. Authentication should be better as well, and encryption is something that should be added too. We should also log information like IP's so we can handle attacks or conduct IP bans.

TODO LIST:

- [x] Add IP Logging
- [ ] Fix registration
- [ ] Encrypt user data and IP's
- [ ] Implement ratelimits
- [ ] Restification

**Comment by dawnofmidnight** [comment]
I'll be adding an admin dashboard to help better manage this data.

**Comment by Kronifer** [comment]
I'll handle IP logging and encrypting stuff

**Comment by doublevcodes** [comment]
Me and @Evorage0 were working on restification
